### ISSUE TITLE
ChromHMM overlap enrichment

### ISSUE THREAD

**Issue by josruirod** [jernst98/ChromHMM#16]
Hello, I've used ChromHMM with ChIP-seq aligment and identified some chromatin states of interest.

I am interested in the overlapping with other datasets of regions to annotate them according to the segment/state they are located on. OverlapEnrichment seems exactly what I'm looking for, but I think I'm failing to interpret it correctly.

After getting the segmentation I'm using bedtools intersect to get the intersections between my regions and the segments, and be able to affirm a region or a peak is in a certain chromatin state.
However, the overlaps I'm getting don't make sense compared to the plots from OverlapEnrichment. I'm aware this is showing FoldChange computed as specified in the manual, but I'm getting very different results. For example, there's a case where more than half of my regions overlap with a segment which is not enriched according to the figure.

Do you ahve any advice on how should I annotate my regions? Have I missed any option on ChromHMM to get the segments corresponding to certain regions?

Thanks for your work and your time

**Comment by jernst98** [comment]
Hi,

Enrichments by default are computed by overlap at the base level so having lots of short regions that overlap the state, but long regions that have minimal overlap could cause what you describe.
Also if a state covers a majority of the genome then it is possible to not have enrichment even when more than half of bases in your region are covered by the state.

If you can't figure out the issue, then if you can send me a private email with pointers to files sufficient for me to see the issue you are having then it would be easier for me to more precisely tell what the cause is.

ChromHMM does not output the coordinates of the intersections it computes, but it should be possible to get equivalent information using bedtools.

Best,
-Jason
