### ISSUE TITLE
what influence will be made among histone markers  for different  sequencing depth ?

### ISSUE THREAD

**Issue by yuaner90** [jernst98/ChromHMM#4]
Hi,
    my data without control, including seven histone markers and two cell types. These data are different  sequencing depth, I noticed the BinarizeBed parameter output the result of the global average number of reads per bin based on the poisson distribution. Could you explain my doubt about that normalize reads count  among different sequencing depth of histone markers ? Thanks very much !

**Comment by ernstlab** [comment]
Large differences in sequencing depths for the same mark across cell types can confound comparisons between cell types. Differences in sequencing depth between marks can be less of an issue since different marks have other differences to begin with. You can downsample your reads outside of ChromHMM if you want to control for differences in sequencing depth.
