### ISSUE TITLE
Binarized data

### ISSUE THREAD

**Issue by makc-sel** [jernst98/ChromHMM#47]
Hello, I have a file with chromosomes and their lengths, this file also contains contigs and scaffolds, such as NW_****.  I'm trying to make a module that translates bisulfite sequencing into binarized data with some preprocessing, for further merging with data that does not require such preprocessing. But in the process I discovered that the size of the chromosomes does not match. My module returns the number of rows equal to chr/bin_size rounded up + 2 header lines. When binarizing the data (BinarizeBed module), I got binarized data for each chromosome in separate files, but the number of lines in the file does not match the size of the chromosome divided by the size of the bin. For example, chromosome NC_037642.1 has a size of 13896941 nucleotides, when dividing this number by the bin size (by default is 200) we get 69484.705 bins, rounded up we get 694845 bins, in the file that contains binarized data we have 69486 lines, but 2 the first lines are responsible for header (the cell and marks). It is correct? Is this a bug?

**Comment by jernst98** [comment]
This is by design. One reason is if a bin is too small its binarization might not be meaningful in that there would be no power for a present call. The other reason is it would cause the segmentation to extend past the end of the chromosome unless you provide LearnModel/MakeSegmentation with a chromosome length file (this can be specified with the -l chromosomelengthfile option, see manual). If you want to include the last bin in your segmentation and you are using BinarizeBed/BinarizeBam then you should give it a version of your chromosome length files rounded up so the length is perfectly divisible by your binning resolution. LearnModel/MakeSegmentation should still be given a chromosome length file with the actual chromosome lengths.

**Comment by makc-sel** [comment]
Thanks for the detailed answer, it was very helpful!
