### ISSUE TITLE
Coverage as Learnmodel input feature 

### ISSUE THREAD

**Issue by NickPanyushev** [jernst98/ChromHMM#48]
Hi, @jernst98

Thanks for your great work! 

Together with @makc-sel we are working on building models for Apis Mellifera based on 4 Chip-seqs and WGBS data. We noticed that WGBS calls processed similarily to [this](https://www.nature.com/articles/s42003-021-01756-4) paper results in 0, 1 and lots of 2(missing data)

But in case of Chip-seq data input there only 0 or 1 after the binarization. I'd like to also input the information about mapability of regions in the Chip-seq data. This approach will allow to distinguish the bins without peak (0) and bins uncovered by sequencing (2). 

So the question is the following - is it better to

-  create the standalone track with coverage by  binarizing bam of non-antibody control sample 

or 

- to assess the coverage separately and replace zeros by 2's in binarized chip-seq data in low-coverage regions?

**Comment by jernst98** [comment]
For the first proposal, that typically will only allow you to confidently call regions with artifactually high number of reads as opposed to any region that is mappable though this can depend on the sequencing depth of your non-antibody control sample.

For the second proposal, assessing coverage separately and replacing 0's by 2's in binarized chip-seq should work, but be aware this could in effect make ChromHMM less conservative in assigning locations to states associated with multiple marks based on limited or no direct evidence of any mark being present at the location. For instance if an entire bin was labeled as not mappable ChromHMM should in effect interpolate based on the neighboring bins that had coverage instead of assuming the mark was not observed present.

**Comment by NickPanyushev** [comment]
Thank you for the useful comment! 

As far as I understood from your answer, introducing missing values to chip-seq calls may cause incorrect assigning of chromatin states. But this problem will primarily concern only states which are described by the absence of one/multiple of the chip-seq signals.

I'll try to give the example just to make sure I got it right: 

Using the 0/1 chip-seq binarization, we have several states in a given experiment: 

E1 - let it be described by presence of two marks (H3K4me1 and H3K36me3) together
E2 - by presence of H3K4me3 and absence of H3K36me3
E3 - by absence of H3K4me1 and absence of H3K36me3

And on segmentation track we'll get the following states on a chromosomes: 
```
                          E1            E2               E3
---------------|------------------|--------------|---------------|------------------
```
But after the introducing the 2's in H3K4me1 there is a risk in misassigning the boundaries of this E3 state, right?

**Comment by NickPanyushev** [comment]
Your answer created one more question for me. 
Can the ChromHMM distinguish 2 states: 

- the one with no signals (0s) from 2 tracks
- the another with missing data (2s) from the same 2 tracks? 

If not, the idea with introdicing missing data in poorly covered regions lacks sense :(

**Comment by jernst98** [comment]
Do you mean H3K4me1 in your example not H3K4me3 for E2? Also would the missing data for H3K4me1 be at a specific position or all positions? If at a specific position do the other marks also have missing data?

If you have incomplete data there is a risk ChromHMM will give incorrect state assignments regardless of whether you using the 0 or 2 encoding for missing data. Assuming the mark is not present in cases where the location is not mappable might be preferred for some applications if you want to be more conservative in assigning locations to marked states where the location is not mappable.

ChromHMM can distinguish two different positions that have all 0s, and assign them to different states, based on their flanking regions and transition information of the HMM. It can similarly do so for two positions that are assigned all 2s.

**Comment by NickPanyushev** [comment]
Yes, sorry for the typo. I did meant H3K4me1. Now corrected in my previous comment
Just to be concise the supposed binarized input to LearnModel should look like this: 

| H3K4me1 | H3K4me3 | H3K36me1 |
| --------------| -------------- | --------------- | 
| 1 | 0 | 1 |
| 1 | 0 | 1 |
| 1 | 0 | 0 |
| 1 | 0 | 0 |
| 0 | 0 | 0 |
| 0 | 0 | 0 |
| 0 | 0 | 0 |
| 0 | 0 | 0 |

After adding the non-mappable regions to data the data should look like this: 

| H3K4me1 | H3K4me3 | H3K36me1 |
| --------------| -------------- | --------------- | 
| 1 | 0 | 1 |
| 1 | 0 | 1 |
| 1 | 0 | 0 |
| 1 | 0 | 0 |
| 2 | 2 | 2 |
| 2 | 2 | 2 |
| 0 | 0 | 0 |
| 0 | 0 | 0 |

The 2's will be introduced to all histone marks simultaneously because mappability will be assessed by the control (non-antibody) sample. 

So, based on your previous answer - will ChromHMM split the E3 state into 2 states in the second case, am I right? I understand that HMM assigns states not in such straightforward way. I'm just interested how to introduce the information about non-mappable (==blacklisted) regions into the ChromHMM. 
The main point for me - to be able to distinguish the regions with no histone marks and regions with no information about.

**Comment by jernst98** [comment]
While this can depend on the specifics of the model, intuitively in the first case you would be relatively more likely to have state E3 where the 2's are in the second case based on the direct observation of 0's at those positions, while in the second case you would be relatively more likely to still have E2 assignment at those positions as the neighboring observations will get more weight since there are no direct observations.

**Comment by NickPanyushev** [comment]
Thank you very much for your answer!
